import assets from "./assets";
import { TWEETS, EXPLORETWEETS, COMMENTS, PROFILE, TRENDINGLISTS, NOTIFICATION } from "./dummy";

export { assets, TWEETS, EXPLORETWEETS, COMMENTS, PROFILE, TRENDINGLISTS, NOTIFICATION };